### ISSUE TITLE
"System Error" response after query.

### ISSUE THREAD

**Issue by davedavis** [AdobeDocs/analytics-2.0-apis#131]
Hi guys,
Our app stopped working over the weekend. 

JWT request and access token is sent and received fine. When sending the request to the report endpoint, we're now getting a response with an unhelpful message: 

**{'reason': 'There was an error processing your request. Request id: uZdK1wktssgfLZqoIK7phGfMu9MOr6Ck.', 'message': 'System error'}**

The request ID changes each time obviously. 

I'm looking at the insights dashboard for some of our other BUs integrations and they're showing 200 responses being recorded over the weekend, but not ours. 

Is there any way to get any insight into this? Is System error just a generic error, is there something wrong on the endpoint side or is there something wrong with our code? I've rolled back quite a few commits to multiple instances where this was working but I'm getting the same error. 

Any advice would be very much appreciated.

**Comment by davedavis** [comment]
I was passing company ID as org ID

**Comment by stevja1** [comment]
Ah -- good to know. I'm glad you got it figured out.
