### ISSUE TITLE
analytics-2.0-apis/discovery.md endpoint began failing yesterday

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/analytics-2.0-apis#134]
The Discovery API started failing yesterday.  It had been working flawlessly up until the outage. 

GET https://analytics.adobe.io/discovery/me
Fails with response body of:
{
    "errorCode": "500",
    "errorDescription": "Error while resolving get imsOrgs for imsUserId=2B413E7C5BE4905E0A495E88@techacct.adobe.com clientId=27d989b002524ca2bb932254b55a7fc0",
    "errorId": "f82d58ed-8602-4f45-9daf-f4051919cb92"
}

I validated that my bearer token is valid by hitting other API endpoints.

**Comment by mike2184** [comment]
This issue has been fixed. Let us know if you see any other problems. Thanks for your report!

**Comment by stewartschillingsdi** [comment]
Thank you!
