### ISSUE TITLE
Bulk API - Missing documentation for token

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/analytics-2.0-apis#139]
Hello, 

As I am trying to test the new API endpoint : "https://analytics-collection.adobe.io"
The documentation doesn't mention the fact that a token is required for ingesting data through that method (so an Adobe IO authentication). 

Trying a request, the API response was : missing Oauth token.

This has been solved once I send the request with the "Authorization": "Bearer token" element in the header.
If this is true, the documentation should mention the requirement to generate a token before ingesting data (compare to the old Data Ingestion API). 

Thanks for that API. 

Best,

**Comment by theswally** [comment]
Hi @pitchmuc, thank you for notifying us.  We have a section entitled "Authentication" in the docs that explains it, and it's listed in the curl example, but I can see it's not shown in the "Operations" details which clearly makes it confusing.  I will remedy that.

**Comment by pitchmuc** [comment]
Thanks. I see it now in the "Header" table row. That is where I meant it was missing. The hint in the curl is what helped me to debug.
