### ISSUE TITLE
discovery api response

### ISSUE THREAD

**Issue by benrwoodard** [AdobeDocs/analytics-2.0-apis#158]
When requesting the company information using the discovery endpoint, I get a column named 'dbc' in the response.  I don't understand what this stands for but it isn't 100% the same across the companies I'm associated with.

**Comment by mike2184** [comment]
The 'dpc' that is returned in the response stands for Data Processing Center. This is the data center in which the Analytics Company is located. You really shouldn't need to use this on the client side as API calls are automatically routed to the correct dpc.
