### ISSUE TITLE
Tag Creation - Issues (docs & methods)

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/analytics-2.0-apis#213]
Hello, 
Trying to create new tags via API. I have full access to the account but the message that is coming back is : `{'error_code': '403025', 'message': 'Profile is not valid'}`

path used : "/componentmetadata/tags"

message sent: 
```
tagCreationList = [
  {
    "id": 0,
    "name": "segments-review-march2021",
    "description": "string",
    "components": [
      {
        "componentType": "segment",
        "componentId": "s4222_5fc765f29da6950a3c71a25d",
        "tags": [
          "segments-review-march2021"
        ]
      }
    ]
  }
]
```
It is following the [documentation](https://adobedocs.github.io/analytics-2.0-apis/#/component-metadata%20-%20tags/saveTagList)

Has anyone successfully created a new tag via API ?

**Comment by parrish488** [comment]
@pitchmuc the Adobe Analytics 2.0 API documentation was recently updated to have more details around tags: https://www.adobe.io/apis/experiencecloud/analytics/docs.html#!AdobeDocs/analytics-2.0-apis/master/tags.md
