### ISSUE TITLE
Calculatedmetrics ownerId endpoint argument not working as expected

### ISSUE THREAD

**Issue by benrwoodard** [AdobeDocs/analytics-2.0-apis#219]
I've been getting a few conflicting results.  My tests were done from swagger UI and my formatted api calls. 

**ownerId** - When I filter by an owner id that I captured from a non filtered result of calculated metrics data I get a 403 error. I am an admin so I shouldn't get the unauthorized response.  In addition, why would it allow me to pull in the ownerId but not filter on the ownerId?

**Comment by parrish488** [comment]
@benrwoodard the problem here is you're using the `includeType=all` parameter.  If you remove that parameter and you're an admin as you stated, it will work how you expect.
