### ISSUE TITLE
How to format the tagnames

### ISSUE THREAD

**Issue by benrwoodard** [AdobeDocs/analytics-2.0-apis#220]
I'm trying to figure out how to format the tagnames for my api call. It appears from my tests in Swagger that this has to be an exact match (not case sensitive).  Is there a way to format a 'contains' type search?

It seems like it would be possible to filter the results by something like 'partial tag name 1'. I just haven't been able to get this to work. 

Would that be possible under the current structure?

![image](https://user-images.githubusercontent.com/2105463/100517273-76348000-3157-11eb-98c9-225beb861bf8.png)

**Comment by parrish488** [comment]
@benrwoodard you are correct, the search isn't a contains search, it's an exact match.  We've recently expanded the tags documentation: https://www.adobe.io/apis/experiencecloud/analytics/docs.html#!AdobeDocs/analytics-2.0-apis/master/tags.md

Maybe you'll find some methods there useful.
