### ISSUE TITLE
Endpoint : Status for BDIA files

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/analytics-2.0-apis#229]
Hello, 

It seems that there is an endpoint to check status of the file that are being ingested through the bulk-data-insertion API. 
In the documentation, you mention status of the file in a way that I have never been able to receive : 

![image](https://user-images.githubusercontent.com/32903178/85365581-f1996200-b525-11ea-9f7c-2886cdd3b470.png)

Is this something that will come public at some point ? Is there any way to access that report from the endpoints that have been published ? 

The maximum amount of information I can retrieve from the POST method is this: 
![image](https://user-images.githubusercontent.com/32903178/85365669-1c83b600-b526-11ea-8df5-449133aa8271.png)

Is there no way to see the ingestion process ?
The "awaiting processsing" status is a bit unclear to know when they will be processed.
I know there is a "Processing Times" paragraph, but wanted to know if a more granular follow up is possible through "file_id".

If that is not existing. This ticket becomes a feature request ;) 

Thanks

**Comment by theswally** [comment]
Hi Julien,
Where in the documentation did you find that response message?

Thanks,
Bret

**Comment by pitchmuc** [comment]
Hello Bret, 
Yes, I was able to get that response message. 
Thanks !
