### ISSUE TITLE
IMS token failed IMS Facade token validation error using the OAuth flow

### ISSUE THREAD

**Issue by AndersBLindby** [AdobeDocs/analytics-2.0-apis#232]
Hi, 

We run multiple reports during the morning ( 07:00:00 GMT ) . Every day we experience that some reports fail with the error:
**Error: Unknown error status: 401 and msg: {"errorCode":"invalid_token","errorDescription":"IMS token failed IMS Facade token validation","errorId":"auth-36fcadb0-02ae-42a7-9cc7-ab0746c125b8"} failed for company: coopda1, type: Exception**

It appears to be random which reports fail and we have no errors if we run all the same reports later during the day.
So the only difference is the time.

We are using the OAuth flow for login and the endpoint is  https://analytics.adobe.io/api/id/reports

**Comment by saverett** [comment]
Hi @AndersBLindby, how often are you reauthenticating? Most authorization tokens expire after ~24 hours.
