### ISSUE TITLE
Specifying multiple name filters in components GET requests

### ISSUE THREAD

**Issue by goncalocapelalopes** [AdobeDocs/analytics-2.0-apis#239]
Is there a way to specify multiple names of metrics/calculatedmetrics/segments in the respective GET endpoints' parameters so that the response contains data only about the specified components? 
E.g. calling the `\segments` endpoint with parameter `names="segment1,segment2,segment3"` returns a JSON response with data on the 3 segments in it's content.

From what I understand from the documentation we can specify name keywords in the `\segments` endpoint, but the response only contains data on segments that have **all** of the keywords in their names, so if we want multiple segments with completely different names, we have to either do 1 GET request per segment, or do 1 (more if there are more than 1000 total segments) GET request that returns all segments and filter them on client side. 

The same thing happens for `\calculatedmetrics` and the `\metrics` endpoint does not even have a name filter parameter.

**Comment by saverett** [comment]
Hi @goncalocapelalopes, the behavior and workaround you described are correct. Providing an "OR"-type list of names to filter on is not currently supported.

Feel free to submit a feature feedback request for this via [experience.adobe.com](https://experience.adobe.com/) by clicking the question mark icon in the top right of the screen and selecting the "Feedback" tab:
<img width="266" alt="experience adobe com Feedback" src="https://user-images.githubusercontent.com/7605060/142946413-ea9f6baa-a513-4b52-81d2-a656c3d7fb37.png">
