### ISSUE TITLE
Specifying report date format

### ISSUE THREAD

**Issue by goncalocapelalopes** [AdobeDocs/analytics-2.0-apis#244]
Is it possible to specify the format of the date values in the JSON report? 

For example, currently date comes in format `Month Day, Year`. Is it possible to get the date in an ISO 8601 format (`Year-Month-Day`)?

**Comment by saverett** [comment]
Hi @goncalocapelalopes, this functionality is not currently supported.

Feel free to submit a feature feedback request for this via experience.adobe.com by clicking the question mark icon in the top right of the screen and selecting the "Feedback" tab:
<img width="266" alt="experience adobe com Feedback" src="https://user-images.githubusercontent.com/7605060/142943854-3f87d77d-d540-4939-8119-f914ce2d859c.png">
