### ISSUE TITLE
Pagination limit not specified

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics-2.0-apis#252]
In the pagination section I can't find these details:

- what is the "limit" set by default if not specified in the request? 
- what is the max number the user the specify in the "settings.limit" field? (1k, 5k, 10k...)

Thanks

https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/reporting-guide.md#paginating-reports

**Comment by parrish488** [comment]
@angeli-adobe The default limit is 50.  MAX_LIMIT = 50000.  I'll add those to the docs.
