### ISSUE TITLE
Multiple "contains" filter for Data Repair

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/analytics-2.0-apis#253]
Related to [Data Repair API](https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/data-repair.md)

If using the "contains" filter type, can a list of substrings be provided to the filters matchValue, or is there another method to provide 2 or more substrings as the matchValue?

**Comment by gigazelle** [comment]
instead of using `contains`, use the `inList` filter. that should give you exactly what you're looking for.
