### ISSUE TITLE
[Data Repair API] How to delete variables based on the other variables' values.

### ISSUE THREAD

**Issue by Kristudas** [AdobeDocs/analytics-2.0-apis#275]
The Data Repair API provides the possibility to delete variables that have a certain value, but is it possible to delete variables based on the other variables' values?

For example:
### delete values of evar2 when evar2=1234 

**Example**
`{
    "variables": {
        "evar2": {
            "action": "delete",
            "filter": {
                "condition": "contains",
                "matchValue": "1234"
            }
        }
    }
}`

but how can we achieve the below case
### delete all values of evar2 when evar10=1111    ?

**Comment by joshua-harrison-2011** [comment]
@Kristudas, This feature is not supported in the product today.  Please reach out to your Adobe Account team and ask to be connected to the Data Repair product team for more options.

**Comment by Kristudas** [comment]
Thank you @joshua-harrison-2011 and we also have one case where we have to delete thousands of values.
Do we have any other way of deleting those values in bulk mode using Data Repair API?

"evar107": {
      "action": "delete",
      "filter": {
        "condition": "inList",
        "matchValues": ["evar value 1", "evar value 2",........................................................................, evar value 80,000]
      }
    }

It is really hard to put all those values  in filter like shown above

**Comment by joshua-harrison-2011** [comment]
@Kristudas The api supports pattern matching using the "contains", "startswith", and "endswith" filters, which might fit your needs, but the inList filter is limited to 1000 elements."
