### ISSUE TITLE
Documenting UI buttons and options

### ISSUE THREAD

**Issue by johnwight** [AdobeDocs/analytics-2.0-apis#28]
The Adobe I/O rendering does not actually format the text that is styled to indicate it is part of the UI.  Note in the attachment that UI references simply have a gray background and the same font as the rest of the text in the sentences.

The ``` formatting``` that is currently in the markdown is for indicating monospace font (such as Courier for code) does not pass through the Adobe I/O rendering. 

Since UI references are usually **bolded**, I would like to suggest using that convention as it does pass through Adobe I/O rendering.

![ui references](https://user-images.githubusercontent.com/29133525/47033900-2e973980-d133-11e8-9015-21e151c63152.PNG)

**Comment by nateprice7** [comment]
That convention looks ok to me.
