### ISSUE TITLE
Breakdowns not seeming to work correctly

### ISSUE THREAD

**Issue by evanashbrook** [AdobeDocs/analytics-2.0-apis#332]
I am trying to request a breakdown of a dimension by itemId, but it still seems to be just giving the total as if there were no breakdown.  I'm actually looping through a bunch of itemIds to get lots of breakdowns by different items and no matter which itemId I specify, it gives the same data list.  I will share a copy of the request json, a copy of one of the response jsons, and a screenshot of the UI showing the total without the breakdown.

Request Json:

` 
{
  "rsid": "bizjournalsglobal",
  "globalFilters": [
    {
      "type": "dateRange",
      "dateRange": "2022-10-30T00:00:00.000/2022-10-31T00:00:00.000"
    }
  ],
  "metricContainer": {
    "metrics": [
      {
        "columnId": "0",
        "id": "metrics/pageviews",
        "filters": [
          "0"
        ]
      },
      {
        "columnId": "1",
        "id": "metrics/visits",
        "filters": [
          "0"
        ]
      },
      {
        "columnId": "2",
        "id": "metrics/visitors",
        "filters": [
          "0"
        ]
      }
    ],
    "metricFilters": [
      {
        "id": "0",
        "type": "dateRange",
        "dateRange": "2022-10-30T00:00:00.000/2022-10-31T00:00:00.000"
      },
      {
        "id": "1",
        "type": "breakdown",
        "dimension": "server",
        "itemId": "9796960"
      }
    ]
  },
  "dimension": "variables/firsttouchchannel",
  "settings": {
    "dimensionSort": "asc",
    "limit": 50000
  }
}
 `

Response Json:

`{
  "totalPages": 1,
  "firstPage": true,
  "lastPage": true,
  "numberOfElements": 14,
  "number": 0,
  "totalElements": 14,
  "columns": {
    "dimension": {
      "id": "variables/firsttouchchannel",
      "type": "string"
    },
    "columnIds": [
      "0",
      "1",
      "2"
    ]
  },
  "rows": [
    {
      "itemId": "1",
      "value": "Paid Search",
      "data": [
        1813,
        358,
        312
      ]
    },
    {
      "itemId": "2",
      "value": "Natural Search",
      "data": [
        168594,
        96293,
        91725
      ]
    },
    {
      "itemId": "3",
      "value": "Direct",
      "data": [
        64002,
        31996,
        27222
      ]
    },
    {
      "itemId": "4",
      "value": "Session Refresh",
      "data": [
        10326,
        4726,
        4188
      ]
    },
    {
      "itemId": "6",
      "value": "Referring Domains",
      "data": [
        15173,
        8640,
        8358
      ]
    },
    {
      "itemId": "7",
      "value": "Editorial Email",
      "data": [
        48942,
        28343,
        25146
      ]
    },
    {
      "itemId": "8",
      "value": "Marketing House Ad",
      "data": [
        33,
        31,
        30
      ]
    },
    {
      "itemId": "9",
      "value": "Other Campaigns",
      "data": [
        2094,
        1290,
        1159
      ]
    },
    {
      "itemId": "10",
      "value": "Marketing Email",
      "data": [
        363,
        126,
        110
      ]
    },
    {
      "itemId": "11",
      "value": "Paid Social Media",
      "data": [
        5681,
        3389,
        3319
      ]
    },
    {
      "itemId": "13",
      "value": "Syndication Partners",
      "data": [
        18495,
        10971,
        10619
      ]
    },
    {
      "itemId": "14",
      "value": "RSS",
      "data": [
        1237,
        726,
        676
      ]
    },
    {
      "itemId": "16",
      "value": "Google AMP",
      "data": [
        16613,
        15193,
        14891
      ]
    },
    {
      "itemId": "18",
      "value": "Social Media",
      "data": [
        133814,
        80195,
        77496
      ]
    }
  ],
  "summaryData": {
    "filteredTotals": [
      487180,
      282277,
      265251
    ],
    "totals": [
      487180,
      282277,
      265251
    ]
  }
}
`

And here you can see the same number circled here, and in the response json after "Natural Search".
Still fairly convinced this is my own fault, but I haven't been able to find my error, so maybe you guys can.  Thanks in advance.  Sorry if trivial.

![FirstTouchChannel_NoBreakdown_Edit](https://user-images.githubusercontent.com/84294020/199078258-a41435f6-4747-464f-8d9f-c119cb43baf6.png)

And like I said, no matter which ItemId I put in there, I get that same total.  My guess is that when a particular error in the request body is sent, the api disregards the breakdown, and just sends the totals for that dimension.  But like I said, I haven't been able to figure out just what the error could be.  I've used other calls to get the itemIds so I know they are legit and I even changed them first into integers, and then back into strings, to get rid of the floaty ".0" at the end.  It also ran previous with the floaty bit, so I think I've made sure I've exhausted data type errors.  Well let me know if you guys figure anything out and thanks in advance... again. lol.

**Comment by parrish488** [comment]
A couple of things here.  I think for a breakdown, you'll want to put it in the global filters.  Also the dimension you're using is "server", but I think the value would at least need to be prepended by "variables/" to work.  Give that a try as well and see if it helps.
