### ISSUE TITLE
Report suites API header values

### ISSUE THREAD

**Issue by ayanared** [AdobeDocs/analytics-2.0-apis#334]
Issue in /src/pages/guides/endpoints/vrs/index.md

**tldr; How should I make the request to get the report suite id's available for a given company?**

I am looking at the docs for the Report suites API.  I can see what the url needs to be to make this request, but I do not know what the headers should be.  Some of the other guides are more specific about the x-api-key value.  What should the headers be to make this request?

**Comment by gigazelle** [comment]
There are only two required headers:
- The `x-api-key` is the client ID in the Adobe developer console.
- The `Authorization` header is the access token you generate, or you can snag the one generated using the API Reference 'Try it out' feature.
See the getting started guide for more information: https://github.com/AdobeDocs/analytics-2.0-apis/blob/main/src/pages/guides/index.md

**Comment by gigazelle** [comment]
JWT and OAuth are separate authentication methods. Regardless of which authentication method you choose, they both require an `Authentication` header.

See the docs on [OAuth authentication](https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/AuthenticationOverview/OAuthIntegration.md) or [JWT authentication](https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/JWT/JWTCertificate.md), depending on which authentication method meets your organization's use case.

**Comment by mike2184** [comment]
We recently released a new OAuth server to server type which is much simpler to use than JWT. Docs can be found here: https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/#oauth-server-to-server-credential
