### ISSUE TITLE
Calculated Metrics - ownerId filter privileges 

### ISSUE THREAD

**Issue by MisterPhilip** [AdobeDocs/analytics-2.0-apis#337]
This is largely a duplicate of #219 but I cannot add comments/re-open it. 

When querying calculated metrics, I am able to query all without a problem. If I try to limit by an ownerId, I get a 403 error. 

If I run `includeType=all`, it works as expected, returning a full list of calculated metrics
`/api/companyid/calculatedmetrics?locale=en_US&limit=10&page=0&includeType=all`

```json
{
    "content": [
        {
            "rsid": "xxxx",
            "id": "cm300004469_57df741fxxxx",
            "name": "Crash Rate (Mobile)",
            "description": "",
            "owner": {
                "id": 987654
            },
            "polarity": "positive",
            "precision": 2,
            "type": "percent"
        },
        "etc...."
    ],
    "totalPages": 5,
    "totalElements": 43,
    "number": 0,
    "numberOfElements": 10,
    "firstPage": true,
    "lastPage": false,
    "sort": null,
    "size": 10
}
```

If I try to add a filter for `ownerId=12345`, 
`/api/companyid/calculatedmetrics?locale=en_US&limit=10&page=0&includeType=all&ownerId=12345`

I receive the following error:
```json
{
    "errorCode": "insufficient_access",
    "errorDescription": "Non admin users cannot retrieve calculated metrics for other users",
    "errorId": "556e7585-17e7-4117-9df2-5cdd68622cff"
}
```

If I removed `includeType=all`, it returns the same error.
`/api/companyid/calculatedmetrics?locale=en_US&limit=10&page=0&ownerId=12345`

Other filters (`tagNames`, `approved`, etc.) all work as expected, just not `ownerId`. The only mention of "admin" on the calculatedmetrics page is for `includeType=all`. Additionally, if `includeType=all` works, the expectation that I can edit/filter for other users calculated metrics via the `ownerId=` param should also work, correct? Or are there more steps to get that in place that should be included in the documentation?  

In case it makes a difference, the product profile has every permission enabled, auth type is JWT.

**Comment by parrish488** [comment]
@MisterPhilip there's a bug in calc metrics where it's allowing includeType=all for all users and is not checking for admin on that.  We will fix that, which means includeType=all will start to fail for this user unless they are made an admin for your analytics product.  At that point, includeType=all and the ownerId filter will work as you expect.

**Comment by parrish488** [comment]
The bug fix for this will roll out in early January.
