### ISSUE TITLE
Endpoint for Retrieving Virtual Reporting Suite Results in a 404

### ISSUE THREAD

**Issue by joshsowalsky** [AdobeDocs/analytics-2.0-apis#366]
Issue in /src/pages/guides/endpoints/vrs/index.md

None of these requests are working: https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/vrs/#retrieve-a-single-virtual-report-suite

**Comment by mike2184** [comment]
The documentation on this page is missing /api/{GLOBAL_COMPANY_ID} from these paths. 

They should look like this:
GET https://analytics.adobe.io/api/{GLOBAL_COMPANY_ID}/reportsuites/virtualreportsuites/

I will get it updated.

You can always see examples of how to call the virtual report suite APIs (and the other APIs) by using the Swagger UI: https://adobedocs.github.io/analytics-2.0-apis/?urls.primaryName=Report%20Suite%20APIs#/Virtual%20Report%20Suites

**Comment by gigazelle** [comment]
Fixed with 2ffa0a2
