### ISSUE TITLE
Issue in /src/pages/guides/endpoints/bulk-data-insertion/endpoints.md

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/analytics-2.0-apis#387]
### Expected Behaviour
The Prerequisite link to point to the prerequisite page (Getting started? https://developer.adobe.com/analytics-apis/docs/2.0/guides/)

### Actual Behaviour
The Prerequisite link pointing to the container page (https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/bulk-data-insertion/endpoints/)

#### Steps to Reproduce
1. Navigate to https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/bulk-data-insertion/endpoints/
2. Click the "Prerequisite" link.
3. Outcome: the link is pointing to the page itself.

#### Sample Code that illustrates the problem
![image](https://user-images.githubusercontent.com/100088147/236912811-4a589da4-4af7-4ab7-a322-ddcf28cc7ea8.png)

**Comment by bretswalberg** [comment]
Thanks for reporting this, Alberto.  I have submitted a fix to the doc repo, should be published in the next 24 hours.

**Comment by gigazelle** [comment]
Merged #388. Thank you!
