### ISSUE TITLE
Does this API give access to documents on an iPad using adobe cloud?

### ISSUE THREAD

**Issue by datatalking** [AdobeDocs/analytics-2.0-apis#422]
There were no open issues

[Adobe URL](https://developer.adobe.com/analytics-apis/docs/2.0/guides/use-cases/python/)of documentation issue I found but I'm not sure that applies to my use case

## Description
I have client data on an iPad and the documents, books, and files contained within are needing to be organized and analysis run on them.

Is this API going to be the right connection point for this application?

**Comment by ridmaur** [comment]
Hi @datatalking Trying to interpret your issue. Can you elaborate as I am not sure I fully understand what is the issue here?

**Comment by ridmaur** [comment]
No clarification on the question, closing the issue
