### ISSUE TITLE
Classification API missing endpoints

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/analytics-2.0-apis#423]
## URL of documentation issue
https://adobedocs.github.io/analytics-2.0-apis/?urls.primaryName=Classification%202.0%20APIs#/Classification%20Dataset 

## Description

On the new classification API, there are several GET parameters but all of them required to know the dataSetId of these classification datasets. 
However, there is no main GET endpoint documented that just give us the list of the datasetId that we can retrieve.

**Comment by johnwight** [comment]
Hi @pitchmuc, please refer to the endpoint guide for Classifications, which contains instructions for the GET all classification datasets: https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/classifications/#get-all-classification-datasets

Thank you.

**Comment by ridmaur** [comment]
Consider this issue closed.
