### ISSUE TITLE
Classifications API > Typo in endpoint references

### ISSUE THREAD

**Issue by fajitamondays** [AdobeDocs/analytics-2.0-apis#430]
## URL of documentation issue
https://github.com/AdobeDocs/analytics-2.0-apis/tree/main/src/pages/guides/endpoints/classifications
https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/classifications/

## Description
Published public documentation for Classification 2.0 endpoints appear to be missing the letter "s" from the word "classifications" base API path in references to various applicable endpoints. This results in 404 responses from the API when attempting to interact with the API endpoints.

**API base path as currently documented:** /classification/
**Expected/functional path**: /classification**s**/

Note: The Swagger interface (via https://adobedocs.github.io/analytics-2.0-apis/classification.json) has the correct references without the typo.

**Comment by johnwight** [comment]
@fajitamondays thank you for your message. Can you clarify something? Are you stating that the typo in the URL is in the endpoint guide for classifications: https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/classifications/
OR
Is it in the swagger.json (reference file): https://adobedocs.github.io/analytics-2.0-apis/?urls.primaryName=Classification%202.0%20APIs#/Classification%20Job

Thanks.

**Comment by fajitamondays** [comment]
Hello John - I'm seeing the typos in the former. The reference Swagger file for the Classifications API seems to be correct.

**Comment by ridmaur** [comment]
@fajitamondays Overlooked your pull request, so made the changes on a separate commit. Now published so all should be now point to `/classifications/` endpoints in the QuickStart Guide. Please close the issue if you’re ok with it

**Comment by fajitamondays** [comment]
@ridmaur Thank you. Looks good now.
