### ISSUE TITLE
Issue in /src/pages/guides/endpoints/bulk-data-insertion/mcseed.md

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/analytics-2.0-apis#433]
## URL of documentation issue
https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/bulk-data-insertion/mcseed/

## Description
The process requests to "Communicate your intent to use this feature to the BDIA team".
But it's not clear who the BDIA team is. Is the client requested to open a support ticket?
Could you please integrate such information in the documentation?

Thanks,
Alberto

**Comment by ridmaur** [comment]
The BDIA team is the team responsible for the Bulk Data Insertion API and its associated format. See https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/bulk-data-insertion/file-format/

Updated documentation accordingly.

**Comment by decaroa** [comment]
Hey Rob.
Thanks for chiming in.
Not sure if you have pushed the updates already.
From what I get I have the same concern:

![image](https://github.com/AdobeDocs/analytics-2.0-apis/assets/100088147/cd24ed20-10e8-4727-a7e2-90b6a65891b1)

That is: who is the BDIA team? As a client, should I open a ticket? As a consultant who should I reach out to?
Do you think a more explicit statement like "Open a support ticket to have the customer ID type set up" would be appropriate?

Alberto

**Comment by ridmaur** [comment]
@decaroa Apologies for picking up this late.... but I do think **the team** refers to the team within the customer organisation that is responsible for using and building integrations based on the Bulk Data Insertion API. And not so much referring to an Adobe team.
