### ISSUE TITLE
Issue in /src/pages/guides/oauth.md: Deprecated JWT example in OAuth examples section

### ISSUE THREAD

**Issue by dbrakman** [AdobeDocs/analytics-2.0-apis#438]
## URL of documentation issue
https://developer.adobe.com/analytics-apis/docs/2.0/guides/oauth/#example-code

## Description
The Example Code section in the OAuth guide links to examples of deprecated JWT authentication instead

**Comment by johnwight** [comment]
Thank you for letting us know. This has been updated and changes should appear within a few days.
