### ISSUE TITLE
New or updated images for Tips document

### ISSUE THREAD

**Issue by johnwight** [AdobeDocs/analytics-2.0-apis#53]
I wonder if it will work to present updated and new images for merging through "Issues." It seems to add a bunch of stuff to the filename so maybe not, but may be worth a try. I have attached them below:

![tips_try_it_out_button](https://user-images.githubusercontent.com/29133525/49835506-a319dd80-fd5c-11e8-94e2-387236d42bd5.PNG)
![tips_copy_json](https://user-images.githubusercontent.com/29133525/49835507-a319dd80-fd5c-11e8-8c14-c90cb1013b10.png)
![tips_create_new_project](https://user-images.githubusercontent.com/29133525/49835508-a319dd80-fd5c-11e8-8da7-d1343bb90bed.png)
![tips_debug_link](https://user-images.githubusercontent.com/29133525/49835509-a319dd80-fd5c-11e8-94a1-374b66414d6a.png)
![tips_debug_text](https://user-images.githubusercontent.com/29133525/49835510-a319dd80-fd5c-11e8-829f-1b933eedfdd3.png)
![tips_open_dev_tools_pc](https://user-images.githubusercontent.com/29133525/49835511-a319dd80-fd5c-11e8-8342-98932a78d46e.png)
![tips_paste_json](https://user-images.githubusercontent.com/29133525/49835512-a319dd80-fd5c-11e8-83f7-432904d4e891.PNG)
![tips_response_body](https://user-images.githubusercontent.com/29133525/49836718-e8400e80-fd60-11e8-8ea9-56a93a957ef8.png)

**Comment by johnwight** [comment]
Additional update on image tips_response_body.png: I needed to blur the bearer token on the curl request. Please use the image attached to this comment instead of the previously attached. Thanks.

![tips_response_body](https://user-images.githubusercontent.com/29133525/49836627-a4e5a000-fd60-11e8-9097-91ef1a3162de.png)

**Comment by nateprice7** [comment]
@johnwight - This PR is getting old so I am going to close it. If you would like to update these images it would be great if you could submit a PR. I can help walk you through the process of submitting a PR with images if that would help.

**Comment by johnwight** [comment]
@nateprice7 - So, initially I was told not to merge or close my own PRs. Going through the steps is probably not necessary, just updates when processes change, or a doc that notes the change on the process. 

Speaking of process changes, what is the possibility of me putting images directly in to the image folder on the repo?

Thanks.

**Comment by nateprice7** [comment]
@johnwight - I wasn't suggesting that you close your own PRs. This is a github issue with a bunch of images that probably should go into the images folder. It would much easier if you would create a PR to put those images into the images folder so it can be reviewed and merged. I can show you how to create that type of PR if you need a hand.
