### ISSUE TITLE
API 2.0 Documentation Update: Specify Minimum Permissions Required

### ISSUE THREAD

**Issue by ratclifftom** [AdobeDocs/analytics-2.0-apis#69]
he documentation page https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/jwt.md describes the profile/permission requirements 

> Note: As part of the process of creating your JWT client, you need to select product profiles to be associated with your integration. Be sure that the product profiles have the correct Adobe Analytics permissions to access the Adobe Analytics APIs.

I think we should provide more information than this, because it took me a lot of time and experimentation before I was able to land on the permissions that were required.

I found that there are 5 sections underneath a profile in the Analytics Admin:

- Report Suites
- Metrics
- Dimensions
- Report Suite Tools
- Analytics tools

In order to get my adobe.io integration to work, I had to add the following permissions in a profile that was added under "Developer" in the Exp Cloud admin.

1. add the proper report suites under "Report Suites"
2. add the proper metrics needed under "Metrics"
3. add the proper dimensions needed under "Dimensions"

It doesn't appear that I needed to add any permissions under "Report Suite Tools” or “Analytics tools”.   I should admit that I'm still new to the API 2.0, however, I can confirm that the settings above allowed me to successfully make API calls (including ones with segments)

After a profile with these permissions has been created, then I was able to associated that profile with my user's integration in the adobe.io console and was then able to make API calls.

I think it would be extremely helpful for the other/future users of the API 2.0 if we clearly spelled this sort of thing out.

**Comment by stevja1** [comment]
https://github.com/AdobeDocs/analytics-2.0-apis/pull/77
